export const PROVINCIAS = [
    "Seleccioná tu provincia",
    "Buenos Aires",
    "CABA",
    "Catamarca",
    "Chaco",
    "Chubut",
    "Córdoba",
    "Corrientes",
    "Entre Ríos",
    "Formosa",
    "Jujuy",
    "La Pampa",
    "La Rioja",
    "Mendoza",
    "Misiones",
    "Neuquén",
    "Río Negro",
    "Salta",
    "San Juan",
    "San Luis",
    "Santa Cruz",
    "Santa Fe",
    "Santiago del Estero",
    "Tierra del Fuego",
    "Tucumán",
  ];
  
  export const OBRAS_SOCIALES = [
    "Seleccioná tu obra social",
    "Sin obra social",        
    "OSDE",
    "Swiss Medical",
    "Galeno",
    "Medifé",
    "IOMA",
    "PAMI",
    "Unión Personal",
    "Accord Salud",
    "Avalian",
    "Federada Salud",
    "Medicus",
    "Omint",
    "Sancor Salud",
  ];